### ISSUE TITLE
Problem converting DLC textures 

### ISSUE THREAD

**Issue by amornthep144** [Atvaark/BinderTool#11]
there seems to be a problem in converting the DLC textures from tpf, i'm unable to read any of the resulting files.

**Comment by amornthep144** [comment]
heres some of the files if you need to look into them
https://drive.google.com/open?id=0B10fLkPZEm01bGx4OFNzMVZHYms

**Comment by Atvaark** [comment]
That's not related to this tool. Your DDS reader is broken.

See:
![output](https://cloud.githubusercontent.com/assets/5101884/19714588/b983372c-9b4f-11e6-82d7-28a550392a4a.png)
