### ISSUE TITLE
Outdated dictionary

### ISSUE THREAD

**Issue by Wulf2k** [Atvaark/BinderTool#12]
I've made my version of the dictionary file available at http://wulf2k.ca/PC/DaS3/dictionary.csv

Let me know if you're not interested in contributions, but that restores Data2 to 100% extraction as well as adding a bunch of random new names.

**Comment by Atvaark** [comment]
Thanks a lot! I'll add them to the next release.

Would you mind taking a look at the file names in the DLC archive?

**Comment by Wulf2k** [comment]
I just updated my copy of the CSV again (same link), probably for the last time in a while.

I don't have the DLC yet and probably won't for a while, so I can't dig into those yet.

**Comment by Atvaark** [comment]
Thanks anyway. I don't own it either.

I added the new file names to the new version [v0.4.2.1](https://github.com/Atvaark/BinderTool/releases/tag/v0.4.2.1)
