### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by johndostarter** [Atvaark/BinderTool#13]
Hi Atvaark,

I am very sorry to bother you but I'd like to ask you a little help here. 
I have zero experience in programming and such and I've been reading the instructions back and forth but haven't been able to use BinderTool 0.3 to extract my (original DSII for PC) GameDataEbl.bdt. I have tried Visual studio to open the BinderTool.csproj file and somehow create an exe file but I really can't figure out the steps here. Would it be too much to ask if you could help me unpack the GameDataEbl.bdt? I was looking for the Executioner's Chariot, which I believe to be c6191=Executioner's Chariot (according to this list: http://forum.xentax.com/viewtopic.php?f=16&t=7876&start=255 made by dib91).
I even tried using version 0.4.2 which has an exe file and then move the GameDataEbl.bdt, GameDataEbl.bhd and GameDataKeyCode.pem to the same folder as BinderTool and then drag and drop the bhd file to the exe but all it does is create an empty folder in the same directory with nothing inside.
I'd really appreciate all the help you could give me! 
Thank you so much!

**Comment by Atvaark** [comment]
Hey,

you should find a pre-compiled 0.3 exe on the releases page of this repo.

To unpack a bdt file you should only have to drag and drop the .bdt file on BinderTool.exe.

If nothig gets unpacked you have to open a command prompt (windows key + R -> cmd -> enter key) first. Then paste the path to BinderTool.exe followed by a space followed by the path to the bdt file. If an error occurs it will get printed to the console. You'd have to send me that error message so I can see what the issue is.

**Comment by johndostarter** [comment]
Hi again,

Thank you so much for getting back to me! Thanks to you, I was able to get to the c6191.bnd and c6191.texbnd files I was looking for and then further unpacked them (see image bellow) by using the Bindertools 0.3 and the pre-compiled exe (I replaced the Dictionary also) on the original Dark Souls II (GameDataEbl.bdt).

However, when I run zaramot's Dark Souls III maya script (which should allow importing files to max from DSII) nothing shows up, although there are files inside that folder that match the extension you have there:

[img]https://i.imgsafe.org/c85fc2f7b7.jpg[/img]

Am I doing something wrong? 
Is there a way to view the files and convert them to max, maya or simply an obj file?

Thank you again!

**Comment by johndostarter** [comment]
Hi again,

Thank you so much for getting back to me! Thanks to you, I was able to get to the c6191.bnd and c6191.texbnd files I was looking for and then further unpacked them (see image bellow) by using the Bindertools 0.3 and the pre-compiled exe (I replaced the Dictionary also) on the original Dark Souls II (GameDataEbl.bdt).

However, when I run zaramot's Dark Souls III maya script (which should allow importing files to max from DSII) nothing shows up, although there are files inside that folder that match the extension you have there:

[img]https://i.imgsafe.org/c85fc2f7b7.jpg[/img]

Am I doing something wrong? 
Is there a way to view the files and convert them to max, maya or simply an obj file?

Thank you again!

**Comment by Atvaark** [comment]
Did zaramot perhaps release a script that is compatible with the DS2 files?

I haven't checked if there were changes to the model files between DS2 and DS3 but it's likely that the tool you are using isn't backwards compatible.

**Comment by johndostarter** [comment]
I was looking through the thread and I can't seem to find one although someone mentions that it should work with DS2 files aswell but it doesn't. I'm using max 2012 as requested for compatibility.

I was trying to use Noesis since all I need is an OBJ file to work with but it isn't reading the flv file but it does read all the texture files! Do you know why?

**Comment by johndostarter** [comment]
I tried putting the original python script for Dark Souls inside the python scripts folder (http://www.mediafire.com/view/?zielsq0268il1yu) but when I try to open the FLV file it gives me this error:
https://i.imgsafe.org/c8f0eeadd4.jpg

**Comment by Atvaark** [comment]
Sorry but I can't help you with your noesis / 3ds max / maya issues. You should ask someone that actually worked on these tools or did some related work like Jed Lang.
