### ISSUE TITLE
packer???

### ISSUE THREAD

**Issue by ponaromixxx** [Atvaark/BinderTool#14]
Is it possible to repack the file or rebuild on the new ???

**Comment by Atvaark** [comment]
It should be. But not with this tool.

**Comment by ponaromixxx** [comment]
but you can not add your support to the packer? I just do not where it is not found more instrummentov for Dark Coles 3, but you could make out!

**Comment by Atvaark** [comment]
I could if I had the time and would get compensated for it. I won't because it will probably only work with a  heavily modified game which will get you banned the second you use it.
