### ISSUE TITLE
Why doesn't BinderTool extract .dcx files?

### ISSUE THREAD

**Issue by ponaromixxx** [Atvaark/BinderTool#16]
And why does Dark Souls Unpasker not extract .dcx files ????

**Comment by Atvaark** [comment]
I don't get your question. This tool can extract .dcx files.

**Comment by ponaromixxx** [comment]
I'm talking about these files:

Msg: /rusRU/item_dlc1.msgbnd.dcx
Msg: /rusRU/item_dlc2.msgbnd.dcx
Msg: /rusRU/menu_dlc1.msgbnd.dcx
Msg: /rusRU/menu_dlc2.msgbnd.dcx
Msg: /rusRU/ngword.msgbnd.dcx

Only these are extracted:

Msg: /rusRU/item_dlc1.msgbnd
Msg: /rusRU/item_dlc2.msgbnd
Msg: /rusRU/menu_dlc1.msgbnd
Msg: /rusRU/menu_dlc2.msgbnd
Msg: /rusRU/ngword.msgbnd
