### ISSUE TITLE
Why doesn't BinderTool not extract .dcx files? to Why doesn't BinderTool extract .dcx files?

### ISSUE THREAD

**Issue by ponaromixxx** [Atvaark/BinderTool#17]
How to extract these files:

Msg: /rusRU/item_dlc1.msgbnd.dcx
Msg: /rusRU/item_dlc2.msgbnd.dcx
Msg: /rusRU/menu_dlc1.msgbnd.dcx
Msg: /rusRU/menu_dlc2.msgbnd.dcx
Msg: /rusRU/ngword.msgbnd.dcx

Only these are extracted:

Msg: /rusRU/item_dlc1.msgbnd
Msg: /rusRU/item_dlc2.msgbnd
Msg: /rusRU/menu_dlc1.msgbnd
Msg: /rusRU/menu_dlc2.msgbnd
Msg: /rusRU/ngword.msgbnd

**Comment by Atvaark** [comment]
The latter files are already extracted from the former files.

*item_dlc1.msgbnd.dcx* **is** a compressed *item_dlc1.msgbnd*.

If you want to extract the compressed .dcx files for whatever reason you're going to have to comment out the part that automatically decompresses dcx files.

**Comment by ponaromixxx** [comment]
Thank you, I did not want to change the whole text!
