### ISSUE TITLE
Helping with the DS dictionary

### ISSUE THREAD

**Issue by theonlyShiro** [Atvaark/BinderTool#20]
Can you me explain how you gonna get the filenames out of Darksouls? im learning things fast im interested in. and i doesnt know how i should contact you without the issue thing. @Atvaark

**Comment by Atvaark** [comment]
See: https://github.com/Atvaark/BinderTool/issues/4

**Comment by knightartorias1** [comment]
dark souls 3 Data1 folder to Data1.bdt repack help please

**Comment by Atvaark** [comment]
Please stop commenting on this repo @knightartorias1.
If this is so important to you maybe you should find a freelancer and pay him/her to help with whatever you want to do.
