### ISSUE TITLE
binder tool repacking?

### ISSUE THREAD

**Issue by knightartorias1** [Atvaark/BinderTool#22]
Hey Atvaark!

As you may have known there's a BinderTool which you can use to extract Dark Souls III files, including the text files. These are stored in .msgbnd files. There are 3 files, namely "item.msgbnd", "menu.msgbnd" and "ngword.msgbnd".

ngword -> This file contains swearing and such, so it must be the file that censors names and nasty stuff.
item -> This contains item and spell names and descriptions, nothing else.
menu -> This contains everything else, from menu text to options to text written with soapstone to NPC speech.

I request a tool which can extract said text from these files, put them back in, and then insert it back into the .bdt file, so that the game could be translated.

**Comment by Atvaark** [comment]
Have you tried using BinderTool to unpack them?

**Comment by knightartorias1** [comment]
Yes. how do repack. please help.
http://www.hizliresimyukle.com/image/2JuWj

**Comment by Atvaark** [comment]
See #14.
