### ISSUE TITLE
Missing decryption key for file

### ISSUE THREAD

**Issue by Kilowog01** [Atvaark/BinderTool#26]
![capturar](https://user-images.githubusercontent.com/16064499/32056421-6263e7a2-ba43-11e7-8b9e-037e52226173.PNG)
Where do I find this key? and where should I place it?

**Comment by Atvaark** [comment]
Could you try if using `bindertool Data1.bhd` works? The key check might be case sensitive.

**Comment by Kilowog01** [comment]
![capturar2](https://user-images.githubusercontent.com/16064499/32100114-a4915930-baf1-11e7-884c-1fe4ce05b2f7.PNG)
Not much has changed, some parts are in Portuguese but I think you can guess what is happening

**Comment by Atvaark** [comment]
Could you check if the issue is still present in the latest version?

**Comment by Kilowog01** [comment]
The last version worked, thank you!
