### ISSUE TITLE
0.5.1 can't unpack vanilla DkS2 GameDataEbl.bdt (Signature was not DCX)

### ISSUE THREAD

**Issue by Jgwman** [Atvaark/BinderTool#27]
@Atvaark it seems that the most recent version of BinderTool is not working correctly for vanilla DkS2, resulting in this error:

https://i.imgur.com/cZDlsur.png

As a side note, massive thanks for your work on BinderTool. I have developed a repacker based on BinderToolCore to use for my level editor thanks to your work.

**Comment by Atvaark** [comment]
Can't reproduce that issue with my files.
- BinderTool 0.5.1.0
- GameDataEbl.bdt with SHA1 59A8C7AFE2219AA44E31681836C1B3CEB9702CBD

Have you modified any files or are you missing the updated dictionary?

**Comment by Jgwman** [comment]
Probably forgot the updated dictionary then, my bad. Thanks for having a look.
