### ISSUE TITLE
Multiple files at once?

### ISSUE THREAD

**Issue by GenericDM** [Atvaark/BinderTool#28]
Is there any way to have multiple files decrypted/decompiled at once?
If not could you add one?

**Comment by Atvaark** [comment]
You mean unpacking multiple files in parallel? You'd have to build your own tool that uses this tool to do that.

**Comment by GenericDM** [comment]
More like specifying a directory then having it decompile everything in there one at a time automatically

**Comment by GenericDM** [comment]
Nevermind, I found out how to do it.
FOR %v IN (*filetype) DO BinderTool.exe %v
