### ISSUE TITLE
Elden Ring keys

### ISSUE THREAD

**Issue by Ekey** [Atvaark/BinderTool#44]
**Data0**

```
-----BEGIN RSA PUBLIC KEY-----
MIIBCwKCAQEA9Rju2whruXDVQZpfylVEPeNxm7XgMHcDyaaRUIpXQE0qEo+6Y36L
P0xpFvL0H0kKxHwpuISsdgrnMHJ/yj4S61MWzhO8y4BQbw/zJehhDSRCecFJmFBz
3I2JC5FCjoK+82xd9xM5XXdfsdBzRiSghuIHL4qk2WZ/0f/nK5VygeWXn/oLeYBL
jX1S8wSSASza64JXjt0bP/i6mpV2SLZqKRxo7x2bIQrR1yHNekSF2jBhZIgcbtMB
xjCywn+7p954wjcfjxB5VWaZ4hGbKhi1bhYPccht4XnGhcUTWO3NmJWslwccjQ4k
sutLq3uRjLMM0IeTkQO6Pv8/R7UNFtdCWwIERzH8IQ==
-----END RSA PUBLIC KEY-----
```

**Data1**
```
-----BEGIN RSA PUBLIC KEY-----
MIIBCwKCAQEAxaBCHQJrtLJiJNdG9nq3deA9sY4YCZ4dbTOHO+v+YgWRMcE6iK6o
ZIJq+nBMUNBbGPmbRrEjkkH9M7LAypAFOPKC6wMHzqIMBsUMuYffulBuOqtEBD11
CAwfx37rjwJ+/1tnEqtJjYkrK9yyrIN6Y+jy4ftymQtjk83+L89pvMMmkNeZaPON
4O9q5M9PnFoKvK8eY45ZV/Jyk+Pe+xc6+e4h4cx8ML5U2kMM3VDAJush4z/05hS3
/bC4B6K9+7dPwgqZgKx1J7DBtLdHSAgwRPpijPeOjKcAa2BDaNp9Cfon70oC+ZCB
+HkQ7FjJcF7KaHsH5oHvuI7EZAl2XTsLEQIENa/2JQ==
-----END RSA PUBLIC KEY-----
```

**Data2**
```
-----BEGIN RSA PUBLIC KEY-----
MIIBDAKCAQEA0iDVVQ230RgrkIHJNDgxE7I/2AaH6Li1Eu9mtpfrrfhfoK2e7y4O
WU+lj7AGI4GIgkWpPw8JHaV970Cr6+sTG4Tr5eMQPxrCIH7BJAPCloypxcs2BNfT
GXzm6veUfrGzLIDp7wy24lIA8r9ZwUvpKlN28kxBDGeCbGCkYeSVNuF+R9rN4OAM
RYh0r1Q950xc2qSNloNsjpDoSKoYN0T7u5rnMn/4mtclnWPVRWU940zr1rymv4Jc
3umNf6cT1XqrS1gSaK1JWZfsSeD6Dwk3uvquvfY6YlGRygIlVEMAvKrDRMHylsLt
qqhYkZNXMdy0NXopf1rEHKy9poaHEmJldwIFAP////8=
-----END RSA PUBLIC KEY-----
```

**Data3**
```
-----BEGIN RSA PUBLIC KEY-----
MIIBCwKCAQEAvRRNBnVq3WknCNHrJRelcEA2v/OzKlQkxZw1yKll0Y2Kn6G9ts94
SfgZYbdFCnIXy5NEuyHRKrxXz5vurjhrcuoYAI2ZUhXPXZJdgHywac/i3S/IY0V/
eDbqepyJWHpP6I565ySqlol1p/BScVjbEsVyvZGtWIXLPDbx4EYFKA5B52uK6Gdz
4qcyVFtVEhNoMvg+EoWnyLD7EUzuB2Khl46CuNictyWrLlIHgpKJr1QD8a0ld0PD
PHDZn03q6QDvZd23UW2d9J+/HeBt52j08+qoBXPwhndZsmPMWngQDaik6FM7EVRQ
etKPi6h5uprVmMAS5wR/jQIVTMpTj/zJdwIEXszeQw==
-----END RSA PUBLIC KEY-----
```
**SD/SD**
```
-----BEGIN RSA PUBLIC KEY-----
MIIBCwKCAQEAmYJ/5GJU4boJSvZ81BFOHYTGdBWPHnWYly3yWo01BYjGRnz8NTkz
DHUxsbjIgtG5XqsQfZstZILQ97hgSI5AaAoCGrT8sn0PeXg2i0mKwL21gRjRUdvP
Dp1Y+7hgrGwuTkjycqqsQ/qILm4NvJHvGRd7xLOJ9rs2zwYhceRVrq9XU2AXbdY4
pdCQ3+HuoaFiJ0dW0ly5qdEXjbSv2QEYe36nWCtsd6hEY9LjbBX8D1fK3D2c6C0g
NdHJGH2iEONUN6DMK9t0v2JBnwCOZQ7W+Gt7SpNNrkx8xKEM8gH9na10g9ne11Mi
O1FnLm8i4zOxVdPHQBKICkKcGS1o3C2dfwIEXw/f3w==
-----END RSA PUBLIC KEY-----
```

**Comment by TBulbaDB** [comment]
How do you extract the files? I've found these keys, can decrypt the bhd files, but no joy on extracting the bdt files so far.

**Comment by Atvaark** [comment]
Thanks. Did you find the UserData and Regulation keys?

**Comment by Ekey** [comment]
> Thanks. Did you find the UserData and Regulation keys?

**Regulation key**

![reg](https://user-images.githubusercontent.com/1664144/155726836-a5e9aba7-9948-4a0f-8f70-7bfb65421ba7.png)

```
unsigned char reg_key[32] =
{
    0x99, 0xBF, 0xFC, 0x36, 0x6A, 0x6B, 0xC8, 0xC6, 0xF5, 0x82, 0x7D, 0x09, 0x36, 0x02, 0xD6, 0x76,
    0xC4, 0x28, 0x92, 0xA0, 0x1C, 0x20, 0x7F, 0xB0, 0x24, 0xD3, 0xAF, 0x4E, 0x49, 0x3F, 0xEF, 0x99
};
```

**Network key**

`he2WGvQXWXzeQxL2`

**Comment by systemsiteseason** [comment]
32 bytes for regulation key

**Comment by xxj222good** [comment]
> 
Elden Ring keys is useful, Thanks!

Maybe BHD5 format in Elden Ring is different from that in Sekiro, DS3 when I unpack Data0 using Elden Ring keys. Error occurs  in FileHeader reading(BHD5.cs). Do you know the relevant format information?

**Comment by barnett2010** [comment]
How to update this tool

**Comment by xlj44400** [comment]
how to use those keys? who has Elden Ring language pack to share

**Comment by morriu** [comment]
How do I get a list of files and create a dictionary.cs file?
Should I use bhd files? 
Some of the information in bhd seems to be encrypted.

**Comment by Ekey** [comment]
The field of `FileNameHash` in `Bhd5BucketEntry` is now 64 bit, so I'm still looking for new hash algorithm :eyes:

**Comment by Ekey** [comment]
If anyone is interested hash algo for Elden Ring

```
public static UInt64 iGetHash(String m_String)
{
    UInt64 dwHash = 0;
    for (Int32 i = 0; i < m_String.Length; i++)
    {
        dwHash = m_String[i] + 133 * dwHash;
    }

    return dwHash;
}
```

**Comment by sanktanglia** [comment]
whats the process like for finding new filenames?

**Comment by sanktanglia** [comment]
also when i change FileNameHash  to a uint64 i get parsing errors immediately after

**Comment by sanktanglia** [comment]
so I think i got the parsing working now, but looks like the dcx files have a new compression type, KRAK, i assume kraken?

**Comment by losh11** [comment]
> so I think i got the parsing working now, but looks like the dcx files have a new compression type, KRAK, i assume kraken?

The sekiro branch include support for kraken compression? https://github.com/Atvaark/BinderTool/commit/30f1455492f60160b7097366f9ba4340e40a649f#diff-424f8b14e549d7c6b0a652b2d0dbb4900a791434a7497bf1c2a91c2dae63a12fR1

Would it be possible for you to fork BinderTool and make commits? I feel like everyone is working individually and it's just going to take longer to get bindertool working with Elden Ring this way.

**Comment by sanktanglia** [comment]
Yeah im planning on pushing up my changes at some point, i just got my first dcx file successfully extracted/decompressed and it looks correct, fails on the next file though so still got some tweaking to do

**Comment by Ekey** [comment]
https://github.com/Ekey/ER.BDT.Tool

Have fun

**Comment by losh11** [comment]
Thanks @ekey

**Comment by mayloglog** [comment]
When unpacking the eldon ring map file, the generated DDS file cannot be recognized by blender, is there some bug?
