### ISSUE TITLE
Request(explanation below) 

### ISSUE THREAD

**Issue by theonlyShiro** [Atvaark/BinderTool#5]
Sorry that im posting it here. 

I wanted to ask you whether you can be a tool or make a support for binder tool . so you can export the dark souls HKX animation files and the right skeleton sorry for the shitty english. 
I wanted to ask you whether you can be a tool or make a support for binder tool . so you can export the dark souls HKX animation files and the right skeleton sorry for the shitty english

**Comment by Atvaark** [comment]
Hey,

adding support for Havok files is out of scope for this tool, so I won't be adding any. You could customize other tools or scripts that works with the Havok files.
