### ISSUE TITLE
I tried to extract the .bdt files from Elden Ring using this command "BinderTool Data2.bdt", but this error happened:

### ISSUE THREAD

**Issue by Arthurfogo7** [Atvaark/BinderTool#51]
"Unable to detect game version. Please specify a game version."
Which game version should I specify? And how would I do that? I need some help.

**Comment by Atvaark** [comment]
See the updated readme by @googleben.
https://github.com/Atvaark/BinderTool/tree/elden-ring

You have to specify `--game EldenRing` in the command line so that the correct encryption key is used. 

Maybe this could be improved with the "auto detect" feature in the future .
