### ISSUE TITLE
Error when trying to extract BND files

### ISSUE THREAD

**Issue by steamedowl** [Atvaark/BinderTool#52]
I'm new at this, so apologies if there's something basic I'm missing. I'm using the Elden Ring branch. As I understand it, any file type ending in BND should be extractable with BinderTool. .geombnd, .mapbnd etc. When I try and run it, I get this error;

Unhandled Exception: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at BinderTool.Program.Process(Options options)
   at BinderTool.Program.Main(String[] args)

I've tried multiple files all of which have thrown this error, and I don't have the expertise to troubleshoot the problem.

**Comment by Atvaark** [comment]
Well I can't exactly troubleshoot this without you sharing the exact command you are trying to execute.

**Comment by steamedowl** [comment]
BinderTool "C:\Users\myname\Desktop\Elden Ring Ripping\Data 0\other\decaltex.tpf" ["C:\Users\myname\Desktop\Elden Ring Ripping\Tast"]

**Comment by Atvaark** [comment]
Did you include these square brackets on purpose? This is not a valid windows path.

These usually just symbolize optional parameters in the documentation. You can omit them if you want the tool to use the default output path.

**Comment by steamedowl** [comment]
Oh dear, that's how inexperienced I am. That was the problem, thanks!
