### ISSUE TITLE
sl2 output binaries

### ISSUE THREAD

**Issue by gtrcoi** [Atvaark/BinderTool#57]
bindertool output 12 binaries with no extensions when targeting sl2 save file, what are these?
[output.zip](https://github.com/Atvaark/BinderTool/files/10528674/output.zip)

Thank you

**Comment by Atvaark** [comment]
These are decrypted save slots and shared savegame data.
There might be be other tools that can further unpack these save slots and repack them like this one https://github.com/tremwil/DS3SaveUnpacker.

**Comment by gtrcoi** [comment]
Thanks, I really want to get more info about how these saves are structured. I want to parse them for completion data, any advice?
