### ISSUE TITLE
DDS file extraction

### ISSUE THREAD

**Issue by ComeOnAndSlam** [Atvaark/BinderTool#6]
I don't know if you already know about this or not, but it seems that some (most) textures do not extract correctly. The broken files extract correctly up until it reaches the file's header, which in working files is "DX1" and in broken files, "DX10". Afterwards, shit goes wild in the DX10 files. [Example](http://puu.sh/oLiHk.png)

**Comment by Atvaark** [comment]
This isn't a BinderTool issue.

Does the tool you are using to view the DX10 DDS files even support DX10 compression?

**Comment by ComeOnAndSlam** [comment]
Are you certain? Because the entirety of the file following that header statement is the exact same line, repeated over and over again. I could be wrong, but it seems to me that regardless of compression methods used, any valid file would have at least some variation, unless it was entirely homogenous, which shouldn't be the case in a nigh-30MB texture. I've tried GIMP, PDN, Photoshop, and the Windows 10 Image Viewer and none of them are capable of opening them, nor does Windows 10 display a thumbnail, as it does for the DX1-labeled images.

If it's not a BinderTool issue, it's not a BinderTool issue, sorry for wasting your time.

**Comment by Atvaark** [comment]
It's most likely a solid black texture. You can try to convert it to another format with [DirectXTex](https://github.com/Microsoft/DirectXTex) and see for yourself.

The other files in that .tpf archive aren't solid black by the way.

**Comment by Atvaark** [comment]
Any news on this?

**Comment by amornthep144** [comment]
Works fine for me though I had to convert to another format in order to read the files.
