### ISSUE TITLE
Please update for the ELDEN RING DLC!  :)

### ISSUE THREAD

**Issue by heyhowareyoubro** [Atvaark/BinderTool#60]
Please update for the ELDEN RING Shadow of the Erdtree DLC! :)

**Comment by HunterAP23** [comment]
Just like it was mentioned in #59 you should probably be using [UXM Unpacker](https://github.com/Nordgaren/UXM-Selective-Unpack) since it's newer and includes more features than this unpacker.

**Comment by Kurainu** [comment]
And as a follow up with @HunterAP23 Answer you can then on the unpacked files use [WitchyBND](https://github.com/ividyon/WitchyBND) to fully unpack/repack/serialize the gamefiles

**Comment by heyhowareyoubro** [comment]
I want to decrypt an encrypted regulation.bin. The witchybnd is unable to do that. UXM Unpacker obviously not meant for it and can't encrypt it. Binder was able to do that before. So that's why I'm asking for the author to update Binder.
