### ISSUE TITLE
Data0 file extraction/unpacking

### ISSUE THREAD

**Issue by theonlyShiro** [Atvaark/BinderTool#7]
i cant extract/unpack the data0 file. Bindertool crash always when i try to extract/unpack it.

**Comment by Atvaark** [comment]
Please attach the error message and the BinderTool version that crashes.

**Comment by theonlyShiro** [comment]
okay here is the error message with data0.bnd and data0.bdt the binderTool version is Bindertool v0.4.1-pre1. i hope thats help to fix my problem
![data0 bhd](https://cloud.githubusercontent.com/assets/15718492/15119350/ca6cd346-1610-11e6-8385-92acd8ae3809.png)
![data0 bdt](https://cloud.githubusercontent.com/assets/15718492/15119351/ca6e531a-1610-11e6-9c42-2e1e2150c79b.png)

**Comment by Atvaark** [comment]
1. You can ignore the first error. There is no way and no need to unpack Data0.bhd at the moment.
2. Does your windows user have read access to Data0.bdt?

**Comment by theonlyShiro** [comment]
yeah my windows have read acces to data.bdt. i have full perms on it

**Comment by Atvaark** [comment]
1. Which command line arguments did you use
2. Do you have full permissions or just read permissions to that file? (You can check that with icacls.exe)
3. Does unpacking any of the other .bdt files in the *\Game* directory work?
4. Have you tried copying Data0.bdt to the same directory as BinderTool.exe?

**Comment by theonlyShiro** [comment]
copying data0.bdt to the same directory as Bindertool.exe has worked and i have .param and .stayparam files unpacked. thank you for helping.
