### ISSUE TITLE
paramdef files

### ISSUE THREAD

**Issue by Pireax** [Atvaark/BinderTool#8]
Hello there,

I am looking for the paramdef files in Data1 but I can't find them, I did see them in the Dictionary.csv though. I also tried looking for them in all the .bnd files in Data1 and every other .bdt. Could you point me in the right direction?

**Comment by theonlyShiro** [comment]
Look into the data0.bdt file there are the paramdef

**Comment by theonlyShiro** [comment]
what you can do with the files paramdef ? I would like to know

**Comment by Pireax** [comment]
I'm working with someone else on a AR Calculator, until now we got the data we needed from memory but using the data from files would be preferable, in a paramdef files is the structure definition of the .param files and a table that connects these structures to ID's  (atleast I hope so). And thats wierd, I just extracted Data1 with the pre-release, only folder there to do with params is the param folder.

**Comment by Atvaark** [comment]
The .paramdef files and other debug related files such as .csv files of all enemies and objects aren't included in the steam main branch. (DSII also didn't include them)

Your best hope is analyzing the regulation .param files manually.

**Comment by Pireax** [comment]
Thanks for looking into it, I'll take a good look at those.
